# Generated by Django 5.2.4 on 2025-08-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_rename_symptoms_triagecase_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagecase',
            name='severity',
        ),
    ]
