# Generated by Django 5.2.4 on 2025-08-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_remove_triagecase_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('psychologist', 'Psychologist')], default='student', max_length=20),
        ),
    ]
